### ISSUE TITLE
Cool project with a big thorn

### ISSUE THREAD

**Issue by mzgnr** [legomushroom/mojs#10]
I noticed we've both been following Pak on twitter (http://twitter.com/muratpak) therefore I believe you already know he's one of the lead motion designers worldwide. Your project is very cool but the similarity and use of the circle as the main icon is extremely bothering in this sense. Specially when it's considered that your project is also a motion design library for the web.
You should consider this issue.

http://i.imgur.com/TrOouDr.png

http://i.imgur.com/hBJN0le.png

http://i.imgur.com/eTcYu99.jpg

**Comment by legomushroom** [comment]
@mzgnr DM'ed to Murat in twitter
