### ISSUE TITLE
Using an image inside a shape

### ISSUE THREAD

**Issue by RobbertWolfs** [legomushroom/mojs#100]
Hi

Is it possible to use an image inside a shape?
I want to create a circle with that has an image. 

Created the [following example](http://imgur.com/a/1PHus) with html5 canvas, but then came across mojs and would like to give it a shot but I need to have the possibility to use an image inside a circle shape.

Thanks

**Comment by legomushroom** [comment]
Hi, Robbert!

Let me create demo for you.

**Comment by legomushroom** [comment]
@RobbertWolfs can you tell me more about what you want to achieve? That's a vinyl disk? What animations you have in mind for it?

**Comment by RobbertWolfs** [comment]
Yeah it is a vinyl disk, I would like to dynamically add the album image om the vinyl and make it spin ;)

Thanks

**Comment by legomushroom** [comment]
@RobbertWolfs I see, give me few minutes

**Comment by legomushroom** [comment]
@RobbertWolfs there is demo without shape, I'm using `Html` module instead because you probably don't need `Shape` for flipping the element - [codepen demo](http://codepen.io/sol0mka/pen/NddRMr?editors=0010).
In case you do want to do the animation of the disk with `Shape` module, I'm creating another demo, just few moments.

**Comment by RobbertWolfs** [comment]
Awesome! Was talking about turning instead of spinning, my bad. But the demo is nice :) Thanks

Would love to see the other demo, just out of interest. If that is not to much of effort for you.

Thanks again for the great and fast response 👍

**Comment by legomushroom** [comment]
Happy to help!

There is another [demo](http://codepen.io/sol0mka/pen/Xppppm?editors=0010). The idea is have the `Html` element and put a `Shape` inside, so the base will be animateable.

**Comment by legomushroom** [comment]
@RobbertWolfs you can even do more crazy things with `stagger` wrapper - [demo](http://codepen.io/sol0mka/pen/zNNZKE?editors=0010).

**Comment by RobbertWolfs** [comment]
@legomushroom Really awesome! Going to experiment with it right now!

One of the best github responses I've got! :1st_place_medal:

**Comment by legomushroom** [comment]
Happy to help, please let me know if something!

**Comment by RobbertWolfs** [comment]
@legomushroom have tried it myself - [codepen demo](http://codepen.io/RobbertWolfs/pen/OWWpxJ)

any remarks?

**Comment by legomushroom** [comment]
@RobbertWolfs nice work! No remarks at all except not using `Shape` module at all for the simple animation - using `Html` is more clear and sufficient - [codepen](http://codepen.io/sol0mka/pen/wggeQO). But of course you can use it your way!

**Comment by RobbertWolfs** [comment]
Yeah was thinking I did too many but did not know how to fix it. Love it that you created a demo to show how it done better 💯
