### ISSUE TITLE
Responsive animation?

### ISSUE THREAD

**Issue by SteffanDonal** [legomushroom/mojs#111]
Hi!

One of the things I'm using your library for is to animate a loading animation.
I'd like it to always fill the screen, no matter which device it's viewed on.

How can I accomplish this?

**Comment by peet86** [comment]
You can use percentage values for positioning, sizing, scaling, etc.. 
Example: http://codepen.io/peet86/pen/jyZOJq

**Comment by legomushroom** [comment]
@peet86 thanks for the response! @SteffanDonal can I get more info? You use `Shape` module or something like that?

**Comment by SteffanDonal** [comment]
Interestingly I opted for a solution where I calculate a scale factor, then have the animation sit within a container scaled by that to fill the screen. Works really well!

**Comment by legomushroom** [comment]
@SteffanDonal awesome, let me know if something!
