### ISSUE TITLE
Tweens not playing in inactive tab

### ISSUE THREAD

**Issue by SudoCat** [legomushroom/mojs#112]
Heya,

I'm using mojs to handle a collection of loading animations, which are used to fade the content in on load. These are working great for the most part, however if I load/refresh the website in an *inactive* tab, and then view that tab after it has finished loading, none of the animations have played, and I get the following error in my console:

```
Uncaught TypeError: Cannot read property 'length' of undefined
at Tweener._restorePlayingTweens
at Tweener._onVisibilityChange
```

Judging by the error, this is related to https://github.com/legomushroom/mojs/issues/58

**Comment by legomushroom** [comment]
Hi Robin!

Looks like the error message got truncated, could you please post the full one?

**Comment by SudoCat** [comment]
Sorry, it looks like I screwed up my markdown formatting. I have updated my original comment to show the whole error.

**Comment by legomushroom** [comment]
Hey @SudoCat, it was fixed already and will be released soon. This happens only when a page is loaded in the background. Sorry for inconvenience and thanks for the heads up!

**Comment by SudoCat** [comment]
Excellent! Let's hope I can get that fix implemented before the client notices ;) And thanks a bunch for all your hard work on mojs - This is the animation library I had been waiting for!
