### ISSUE TITLE
Weird Offset On Simple Ripple Example

### ISSUE THREAD

**Issue by tetreault** [legomushroom/mojs#113]
Hello, 

I'm copying the simple ripple demo pretty much verbatim. When I click, there's weird offsets and it doesn't animate the way it does in the codepen found [here](https://codepen.io/sol0mka/pen/XKdWJg).

When I click where you see the black bar PNG you can see how far away the simple ripple mo.js created is. 
![img1](https://cloud.githubusercontent.com/assets/5934354/22567272/46c3a436-e95d-11e6-946e-dd009f02fcb8.jpg)

Here is the CSS it is generating: 
```css
    position: absolute;
    width: 102px;
    height: 102px;
    margin-left: -51px;
    margin-top: -51px;
    opacity: 1;
    left: 50%;
    top: 50%;
    transform: translate(270px, 106px) rotate(0deg) scale(1, 1);
    transform-origin: 50% 50% 0px;
```

My JS looks like this for it:

```javascript
        //Data - mo.js
 28   const mojsAnimationConfig = {
 29     fill: 'none',
 30     radius: 25,
 31     strokeWidth: {
 32       50: 0
 33     },
 34     scale: {
 35       0: 3
 36     },
 37     angle: {
 38       'rand(-35,-70)': 0
 39     },
 40     duration: 400,
 41     left: 0,
 42     top: 0,
 43     easing: 'cubic.out'
 44   };
 45   const mojsCirleOuter = new mojs.Shape({
 46     mojsAnimationConfig,
 47     stroke: 'cyan'
 48   });
 49   const mojsCircleInner = new mojs.Shape({
 50     mojsAnimationConfig,
 51     radius: {
 52       0: 15
 53     },
 54     strokeWidth: {
 55       30: 0
 56     },
 57     stroke: 'magenta',
 58     delay: 'rand(75,150)'
 59   });
```

And here is the function triggered on click: 
```javascript
           clickIcon: (e) => {
139       e.preventDefault();
140 
141 
142       mojsCirleOuter.tune({
143         x: myIconData.x,//(e.pageX || e.touches[0].pageX),
144         y: myIconData.y//(e.pageY || e.touches[0].pageY)
145       }).replay();
146 
147       mojsCircleInner.tune({
148         x: myIconData.x, //(e.pageX || e.touches[0].pageX),
149         y: myIconData.y //(e.pageY || e.touches[0].pageY)
150       }).replay();
151     }
```

Not only that, but it doesn't really ripple, rather a filled in circle blinks in on the screen. 

This is being run on Chrome Version 55.0.2883.95 (64-bit).

**Comment by legomushroom** [comment]
Hi Stephen!

Could you create `codepen` demo for the issue, it is hard to spot the issue not having the full code?

**Comment by tetreault** [comment]
Hello @legomushroom thanks for the quick reply back. I'll try placing this into a codepen demo, though the project involves websockets so I'm not too sure if it can be distilled into one. I took out the pieces relating to mojs but am not having it working in the [codepen](https://codepen.io/tetreault/pen/PWeRmE). 

I'm not sure if it is any more help, but if it is here is the full [client-side JS in a gist](https://gist.github.com/tetreault/7cc8d5e0f1c1cb56b748e63f425e48cc). 

I copied the simple ripple codepen you made pretty much exactly, only things i changed were the variable names and I didn't use the spread operator. The shapes were created like so: 

```javascript
// in this demo mojsAnimationConfig is OPTS from your Simple Ripple codepen
const mojsCircleInner = new mojs.Shape({
  mojsAnimationConfig,
  radius: {
    0: 15
  },
  strokeWidth: {
    30: 0
  },
  stroke: 'magenta',
  delay: 'rand(75,150)'
});
```

**Comment by tetreault** [comment]
Ah so stupid, my fault. Your demo works, it was because I was adding in the config options object without the spread operator, thus it just was breaking the animation. 

Closing this out now, thanks for the reply and glad my mistake was small :)

**Comment by legomushroom** [comment]
@tetreault oh I see, please let me know if something.
