### ISSUE TITLE
Set Animation Progress

### ISSUE THREAD

**Issue by mateobadillo** [legomushroom/mojs#116]
Hey Legomushroom!

I would like to know if there is an option to put a setProgress() over an animation (it may be my fault for be completely documented). This could be use for example to make forward/backward animations when the user scrolls.

By the way love mojs!

**Comment by legomushroom** [comment]
Hi @mateobadillo! You can use `setProgress` on any module that expects a number in the range from `0` to `1`:

```js
  const burst = new mojs.Burst;
  burst.setProgress(.5);
```

**Comment by mateobadillo** [comment]
Thanks for the quick response!

That raises me a question, does `setProgress` overwrites duration or delay of an animation? Even number of repetitions?

**Comment by legomushroom** [comment]
Nope, it does not overwrite anything, just sets a state of a module. Basically if you have animation from 0px to 200px, setProgress(.5) should set the state to 100px.

**Comment by mateobadillo** [comment]
Okay I understand, but if a have for example 0px to 200px with a duration of 200, repeat 10 times, and a delay of 100. Then for the setProgress(mouseover.xCoordinate/total-view-width) those three attributes would be ignored by the setProgress method, wouldn't be?

**Comment by legomushroom** [comment]
Nope they will be accounted and state will be whatever in the middle of all those periods.

**Comment by mateobadillo** [comment]
Understood, thanks for the discussion! 

Best regards.

**Comment by legomushroom** [comment]
np, please let me know if something
