### ISSUE TITLE
Animating Path one by one

### ISSUE THREAD

**Issue by umairkhantraffic** [legomushroom/mojs#117]
Hi,

I have a SVG with multiple `<path>` elements in it. Is there any way that i can animate them one by one in the order they appear.  Currently i am using the following code:
[https://codepen.io/yarumair/pen/OWBWYW](url)

So currently its animating all the `<path>` element concurrently. Is there any easy/straight way that i can animate them one by one so that once first `<path>` animation is finished the other one will start. I don't want to create separate shapes for each `<path>` element.

P.S. Great library. I have just started working on it yesterday and it's going smooth. Very easy syntax

**Comment by legomushroom** [comment]
Hi, thanks a lot!

I think you should look at `stagger` wrapper which allows dealing with sequence of elements, there is [codepen demo](https://codepen.io/sol0mka/pen/RKejjb?editors=1010).

**Comment by umairkhantraffic** [comment]
WOW! brilliant. Iam in love with mojs

**Comment by legomushroom** [comment]
happy to help!
