### ISSUE TITLE
Safari Dashoffset compatibility

### ISSUE THREAD

**Issue by mateobadillo** [legomushroom/mojs#118]
Hey LegoMushroom

I was trying to animate some paths backwards everything worked fine until I opened it in Safari. Using this codepen you created for another issue [https://codepen.io/sol0mka/pen/RKejjb?editors=1010](url) editors=1010 the problem can be shown. If you change strokeDashoffset to something like `strokeDashoffset: { '-400' : '0' }` the paths don't get drawn well. This only occurs in Safari

Regards!

**Comment by mateobadillo** [comment]
I saw you typed in another issue: "Notice that in my demo it starts from positive 100% due to Safari's strokedash bug with negative numbers". Is there another way around with Safari?

Thanks!

**Comment by legomushroom** [comment]
Hey, @mateobadillo!

That's well known `Safari` issue, it just works weirdly with negative `strokeDashoffset`, so if possible just don't use it, maybe `{ '-400' : '0' }` will work the same in your case?

**Comment by mateobadillo** [comment]
Unfortunately no, the `svg` appears then disappears and then the animation `path` starts. So in `Safari` is not currently possible to fix or to "trick" this behavior?

Thanks for your rapid response @legomushroom!

**Comment by legomushroom** [comment]
No probs :)

> Unfortunately no, the SVG appears then disappears and then the animation path starts.

Not sure I understood this. 

---

Yes, I don't know any reliable method to fix this Safari behavior.

**Comment by mateobadillo** [comment]
Yeah it is difficult to explain in words: check this site: [http://waoo-seller-desarrollo.herokuapp.com/#!/landing/](url) there you can see what I tried to explain.

Oh! okay so I'll keep with "forward" anims!

**Comment by legomushroom** [comment]
Oh I see, you should be able to implement the same animations using `forward` direction. If not, ping me, we will come up with something.

**Comment by mateobadillo** [comment]
You were right simply by doing this ` strokeDashoffset: {'800': '1600'  }` it works in forward direction, thanks for your support @legomushroom ! can't wait to see more modules!

**Comment by Charlie-007-star** [comment]
is there any solution for that yet? I'm in 2022 !

**Comment by Sandstedt** [comment]
@Charlie-007-star 
If you are experience browser issue in Safari, please report them to the Safari Webkit crew. It has nothing to do with Mojs unfortunately. Thanks!
