### ISSUE TITLE
Regenerate and encrypt SauceLabs keys

### ISSUE THREAD

**Issue by riggerthegeek** [legomushroom/mojs#12]
In the .travis.yml file, your SauceLabs keys are open to the public. Regenerate and encrypt it so no-one else can use it - http://docs.travis-ci.com/user/environment-variables/

    - SAUCE_USERNAME='legomushroom'
    - SAUCE_ACCESS_KEY='6982f2ea-fd37-453f-9cc6-58ea67254b66'

**Comment by herrmannplatz** [comment]
:+1:

**Comment by legomushroom** [comment]
You are right, guys. Totally forgot about that, thanks for the alert.

**Comment by legomushroom** [comment]
Good day.

I've added new keys as env variables in repo settings.
Didn't encrypt them cuz, as I got it, encrypted vars will not be added to pull requests, which I still want to run tests for.
Will update `.travis.yml` file on `master` branch on the next merge, the key was regenerated anyways.
I'm closing the issue, if you think this is not secure enough, please reopen.

Thanks for the heads up!

**Comment by riggerthegeek** [comment]
Yeah, that's correct.

If you'd have used the travis gem to encrypt them in your .travis.yml file, that would have been exactly the same. But it's encrypted now which is the main thing
