### ISSUE TITLE
Burst Easing

### ISSUE THREAD

**Issue by vitalej4** [legomushroom/mojs#120]
The `easing: 'linear.none'` parameter doesn't seem to be working on burst. I currently have a burst that consists of 6 small circles spinning repeatedly. I want to set the easing parameter to none so it seems to be one continuous infinite spin. Is this a bug, or something that is not supported in the burst module?

Here is a codepen displaying the issue I'm having: http://codepen.io/jvitale/pen/vgqbpP

**Comment by legomushroom** [comment]
Hi @vitalej4 !

Sorry about the confusion, you can set the easing right on the delta object of the angle: [demo](http://codepen.io/sol0mka/pen/KajEpX).

**Comment by vitalej4** [comment]
Thank you, this resolved my issue.
