### ISSUE TITLE
Are the releases tagged 'prerelease' stable?

### ISSUE THREAD

**Issue by elliottregan** [legomushroom/mojs#123]
I noticed there hasn't been a real release in...over a year, and the API & docs have changed a lot since then. Are those newer 'prerelease' builds stabile enough to use in production?

**Comment by legomushroom** [comment]
Hye @elliottregan!

Until `mojs` will get to `version 1.x.x` the APIs can change drastically. I personally use it in production, but I cautious about all the syntax versions it has.

**Comment by elliottregan** [comment]
@legomushroom Thanks for the followup!
