### ISSUE TITLE
Am I using yoyo correctly?

### ISSUE THREAD

**Issue by dangodev** [legomushroom/mojs#131]
I can’t seem to get `yoyo: true` functioning correctly in the latest mojs version. Example: https://codepen.io/dangodev/pen/JNGOyL.

```
new mojs.Shape({
  duration: 2000,
  fill: { cyan: 'limegreen' },
  radius: { 10: 25 },
  repeat: 99,
  shape: 'circle',
  x: { 0: '-500%' },
  yoyo: true,
}).play();
```

Am I missing something, or simply misunderstanding this option? Thanks in advance.

**Comment by mateobadillo** [comment]
Hey,

Justa change yoyo to isYoyo and it'll work

**Comment by dangodev** [comment]
@mateobadillo youda best! I’ll make a PR to update the docs I was reading.

**Comment by legomushroom** [comment]
Right all `boolean` properties now prefixed with `is`.

**Comment by mateobadillo** [comment]
Glad to help!
