### ISSUE TITLE
I'm not able to solve this

### ISSUE THREAD

**Issue by Tomarnst** [legomushroom/mojs#135]
I'm just trying to learn mo.js and try to move two lines in a logo. Somehow I can't use negative values in my simple script. see [codepen](https://codepen.io/phoney/pen/WjXbQw).

Any pointers to solve this ?

**Comment by gaou-piou** [comment]
const html2 = new mojs.Html({
  el: '#yel-2',
  x: { [-195]: 0, duration: 1500, easing: 'ease.out' } // tried to set this to negative value
}).play();

**Comment by Tomarnst** [comment]
Thanks,

I didn't know I had to use those [minus]

**Comment by legomushroom** [comment]
@gaou-piou thanks for your help!

@Tomarnst you can use negative values with computed properties as @gaou-piou suggested or just use string instead: `{ '-195' : 0}`.

Cheers~
