### ISSUE TITLE
Update tutorials on website

### ISSUE THREAD

**Issue by ibbatta** [legomushroom/mojs#145]
Hi @legomushroom , thanks for this amazing and lovely animation library (I really fell in love on it!!!!)
I am currently studying the animations on your website thanks to the tutorial section and my question is: will be complete in the future? The "step-by-step" method is very efficients and useful, please go on! (I will donate "a coffee" if you need eheheh)

**Comment by legomushroom** [comment]
Hi, Maurizio!

Happy to hear that, thanks a lot! Currently, I'm working on `mojs2` release and I do plan to create a full video course with an in-depth review of it. After that, I will probably update the written tutorials but the video course is the top priority at the moment (which might be helpful for you too :)).

**Comment by ibbatta** [comment]
This is a marvelous news!
Thanks dude you are the best!

**Comment by legomushroom** [comment]
@ibbatta thanks a lot!
