### ISSUE TITLE
.stop() does not update if its not .play() or until .play() is called

### ISSUE THREAD

**Issue by Journeytojah** [legomushroom/mojs#171]
I am trying to have some animations on an onboarding screen on various slides.

I want to .stop() and reset the animations to their initial state while they are off screen.

For example: when going from slide one to slide two, I want the progress to be taken back to 0 on slide one so it will be ready to play from the beginning if the user goes back to it. 

This works fine under ideal circumstances but it does not once the animation reached its end. It jumps from last frame to the first after the animation comes into view and the next .play() is called.

**Comment by xavierfoucrier** [comment]
Do you have a sample code or a codepen that shows the problem you're highlighting?

**Comment by Journeytojah** [comment]
I am using it on an Ionic app, not working well on codepen afaik.

Ill try my best to explain better. 

.stop() only stops and resets the animation if its playing. So after it reaches the end of the animation and .stop() is called it resets everything to progress = 0 after calling .play().

I am trying to have an interaction between the slides. So if the animation on slide 1 is playing and the user starts swiping, the animation pauses; if the user goes to slide 2, the animation on slide 1 resets to initial state and is ready to play.

I have tried placing a button on slide 2 that calls .stop() on the slide 1 animation timeline, but that only happens after the slide comes into view and .play() gets called.

Hope this clears it up.

If needed I will try to get a sample up on codepen or maybe jsfiddle.

Thank you for the help.

**Comment by xavierfoucrier** [comment]
I @Journeytojah, sounds clear :wink: ! I will try to code a sample tonight or tomorrow to check that.

**Comment by Journeytojah** [comment]
Thank you @xavierfoucrier , meanwhile I implemented the animations into the slides without any interaction.

Would not mind them having a split second on the last frame played if they go back to them, and then starting from the start. But smoother would be better.

**Comment by xavierfoucrier** [comment]
I @Journeytojah, I supposed this is a bug inside the library... seems that `setProgress`or `reset` doesn't do the job. The `stop` method work, but are not reseting the tween when the animation is ended.

Anyway, I found a short solution to your problem by "**tuning**" the tween with one of the property/value used on object declaration. Here is a sample code that work like a slider: when the document is clicked, that stops the current tween and gives you the next "slide" tween, etc.

	// triangle shape for slide 01 tween
	const slide01 = new mojs.Shape({
	    shape: 'polygon',
	    points: 3,
	    fill: 'transparent',
	    stroke: '#f6cc00',
	    strokeWidth: { 10 : 2 },
	    radius: { 0 : 50 },
	    duration: 1500
	}).play();

	// square shape for slide 02 tween
	const slide02 = new mojs.Shape({
	    shape: 'polygon',
	    points: 4,
	    fill: 'transparent',
	    stroke: '#509ee2',
	    strokeWidth: { 10 : 2 },
	    radius: { 0 : 50 },
	    angle: { 0 : -360 },
	    duration: 1500
	});

	// pentagon shape for slide 03 tween
	const slide03 = new mojs.Shape({
	    shape: 'polygon',
	    points: 5,
	    fill: 'transparent',
	    stroke: '#19f1ab',
	    strokeWidth: { 10 : 2 },
	    radius: { 0 : 50 },
	    angle: { 0 : 360 },
	    duration: 1500
	});

	// timeline array
	var timeline = [
	    slide01,
	    slide02,
	    slide03
	];

	// current slide index, starts at 0 in an array
	var slide = 0;

	// binds the click event of the document
	document.addEventListener('click', function(e) {

	    // stops the current tween
	    timeline[slide].stop();

	    // tunes the current tween
	    timeline[slide].tune({
	        duration: 1500 // the same duration as before
	    });

	    // next slide (based on timeline length)
	    slide = slide + 1 == timeline.length ? 0 : slide + 1;

	    // plays the next slide tween
	    timeline[slide].replay();
	});

Thanks for your feedback :wink:

**Comment by Journeytojah** [comment]
Wow, thank you so much for the snippet and the effort. I will get this up on monday and get back on how it goes.

Meanwhile, I also e-mailed @legomushroom, i would like to help contribute to this library the best that i can, either with documentation, translations or tutorials. I see great potential in it and enjoy it very much. 

If there's anything i can do to help feel free to contact me.

Have a nice weekend!

**Comment by xavierfoucrier** [comment]
No problem, waiting your implementation test feedback. It's the same for me: I work with this library since last year and I see that the library can evolve in many way. Hope this project will continue to grow up! 👍

**Comment by xavierfoucrier** [comment]
Hi @Journeytojah!
If my answer seems relevant to you, you can close the issue. Thx! :+1:

**Comment by Journeytojah** [comment]
Sorry, @xavierfoucrier , we got carried away with other projects.

The implementation worked great, thanks a lot for the help!
