### ISSUE TITLE
Any way for translate SVG elemements - on IE ?

### ISSUE THREAD

**Issue by Oguima** [legomushroom/mojs#18]
SVG inline elements, cam be tranlated ...
Works fine in: Chrome, Firefox and Safari ...

IE - not transform SVG elements.

Exemple:
http://codepen.io/Oguima/pen/XmvVqQ

**Comment by legomushroom** [comment]
Hey @Oguima !

You mean transform with `CSS` or `JS`?
`SVG` has numerous issues with transforms defined in `CSS`.
Setting transform directly on element with `transform` attribute should work everywhere though:

```html
<g id="termometro" transform="translate(0, -70px)">
```

Thanks

**Comment by Oguima** [comment]
Testing ... Now :D Thanks

**Comment by Oguima** [comment]
I try:
//termometro.style['transform'] = 'translate(0 ,' + -70 + 'px)'; //Ok firefox, safari, chrome... not IE
termometro.setAttribute("transform", 'translate(0, ' + -70*progress + 'px)'); 

Error: Invalid value for <g> attribute transform="translate(0, -70px)"

**Comment by legomushroom** [comment]
@Oguima surely. remove pixels:

```javascript
termometro.setAttribute("transform", 'translate(0, ' + (-70*progress) + ')');
```

**Comment by Oguima** [comment]
Good news for me, work :D.
I have problens with transitions ... 
transition: all 1s;
or
transition: transform 1s;
Via CSS, no work. (For SVG elements)

Via mojs, work, partial. I need more tests for this.
Removed transition ... i try to go to 0 transform ...
Whow to transform to (0,0) ?

```javascript
 new mojs.Tween({
            repeat:   1,
            delay:    0,
            duration: 2000,
            onUpdate: function (progress) {
                termometro.setAttribute("transform", 'translate(0, ' + 1*progress + ')');
            }
        }).run();
```

**Comment by legomushroom** [comment]
```javascript
termometro.setAttribute("transform", 'translate(0, ' + 70*(1-progress) + ')');
```

**Comment by Oguima** [comment]
Works... but 2 times ?!? ...
I removed repeat: 1 ... And Works Fine , thanks
```javascript
termometro.setAttribute("transform", 'translate(0, ' + -70*(1-progress) + ')');
```

**Comment by legomushroom** [comment]
@Oguima exactly. You have `1` repeat loop, so it will run 2 times.

**Comment by Oguima** [comment]
I try with WAAPI, and not work ... with SVG. works fine with divs ...
mojs , works fine with SVG NOW :D 

achievement unlocked:
- SVG transform: translate  on IE

Thanks

**Comment by legomushroom** [comment]
np

**Comment by Oguima** [comment]
Sample Works Fine:  Click on termometer, UP and Down - works on IE.
* SVG transform: tranlate on IE - With: mojs

http://codepen.io/Oguima/pen/WreNVR

**Comment by legomushroom** [comment]
yay!
