### ISSUE TITLE
Burst animation happens twice on ios

### ISSUE THREAD

**Issue by olemartin** [legomushroom/mojs#182]
I am struggling with an issue with Burst.
On every desktop browser, and android phones, the burst is played normally. However, on ios something strange happens:
The animation is ran twice, and the total duration is the duration I sat as a property on children. So, on android there is one burst with a duration of five seconds and on ios the is two bursts with a total duration of five seconds.

The code for the mojs.Burst
```
const mojs = require('mo-js');
        this.burst = new mojs.Burst({
            parent: '#label-' + this.props.id,
            radius: 40,
            degree: 300,
            angle: 120,
            count: 11,
            children: {
                shape: 'line',
                radius: 6,
                scale: 1,
                stroke: this.props.color,
                strokeDasharray: '100%',
                strokeDashoffset: { '-100%': '100%' },
                duration: 5000,
                easing: 'quad.out',
            }
```

The triggering:
```
this.burst.replay();
```

**Comment by eltonmesquita** [comment]
To make things a bit easier for people to help you:
- What iOS version the problem happens?
- can you post a reduced case on codepen or similar service?
- does it happen in a specific scenario?
- does it happens only with burst?

**Comment by olemartin** [comment]
I'll add the codepen later.
So far we've tested it with iPhone X and iPhone 8. Both running ios 11.
I have only used Burst.
The scenario is an onClick event on an image. This is a react-app.
I can send you an url in an email or something if you're interested.

**Comment by olemartin** [comment]
Also happens on iPad with ios 11.2.5

**Comment by olemartin** [comment]
The bug is present here: https://codepen.io/rkhayat/pen/aBpMRr?editors=1010

**Comment by olemartin** [comment]
The bug is also at Chrome on IOS

**Comment by olemartin** [comment]
@eltonmesquita Have you had a chance to look at the codepen?

**Comment by eltonmesquita** [comment]
Nope. Unfortunately this is a pretty messy week for me and my Xcode is broken :(
I'll try it next week, alright?

**Comment by xavierfoucrier** [comment]
Hi @olemartin!

I can't test on iOS for now, sorry, but, can you try to change this:
`strokeDashoffset: { '-100%' : '100%' }`

...into this:
`strokeDashoffset: { 0 : '100%' }`

Thanks for your feedback :wink:

**Comment by xavierfoucrier** [comment]
Tested and working fine on an iPad Pro with iOS 11.2.6: can't reproduce this issue.

**Comment by olemartin** [comment]
Thanks! 
Seems like `strokeDashoffset: { 0 : '100%' }` did the trick. At least on https://codepen.io/rkhayat/pen/aBpMRr?editors=1010

**Comment by xavierfoucrier** [comment]
Very nice! I suspected there was a problem with configuring this property this way. That's cool, thanks for the reply and have a nice day :+1:
