### ISSUE TITLE
How to get things responsive ?

### ISSUE THREAD

**Issue by Tomarnst** [legomushroom/mojs#187]
Hi,

I have been playing around for a while with mo.js. I can't figure out how to make an animation responsive to different screen sizes. For example:
https://codepen.io/phoney/pen/PmdLRM

Thanks

**Comment by xavierfoucrier** [comment]
Hi @Tomarnst,

It depends what you are trying to do, but the responsive layout needs to be done in pure `css` or `js`. If you start with `mojs`, you will probably see that the main starting point is centered to the screen. With that, you can easily tune the size of you animation with the css `scale` property: for example, if your animation is larger than 600px on desktop, you can scale it to 50% to render the same animation on mobile with a width of 300px.

Really, it depends on the case.
Hope this help :wink:

**Comment by Tomarnst** [comment]
Well I try to get the animation to 50% when its on a mobile. I can't find how to do that with css in this case.

**Comment by Tomarnst** [comment]
Hi @xavierfoucrier ,

Thanks I see it now in my case it was putting it into the div id tukku. I was trying to set svg id js-mojs-shape-canvas with the css.

Thanks again.

**Comment by xavierfoucrier** [comment]
You're welcome!
Don't forget to close the issue if all is clear for you :wink:
