### ISSUE TITLE
Broken tutorials page

### ISSUE THREAD

**Issue by hipstermojo** [legomushroom/mojs#188]
Anytime I visit the [tutorials link](http://mojs.io/tutorials/shape/), my Google Chrome crashes. I am using Chrome 66 by the way.

**Comment by xavierfoucrier** [comment]
Hi @hipstermojo!

It works fine for me on Chrome 66. Have you try to open the web developer console via `f11` and see what happens?

Best regards.

**Comment by hipstermojo** [comment]
Hey @xavierfoucrier 

It is still not working for me.
Here's a screenshot from just now.

----

![mojs crash](https://user-images.githubusercontent.com/25569504/39580232-5c26065c-4ef1-11e8-9ee6-70aa40765b27.png)


As you can see, even my DevTools aren't working. :unamused: 

I am on Ubuntu 17.10

**Comment by xavierfoucrier** [comment]
I am working on Windows, but seems like its a Chrome extension or something that interfer with your request. Did you try to open the tutorial in another browser: may be Firefox for Ubuntu?

**Comment by hipstermojo** [comment]
Okay well it works on Firefox. I guess it is just Linux being Linux.

I'll just close this then. Thanks!
