### ISSUE TITLE
Minor typo & Website Suggestion

### ISSUE THREAD

**Issue by donfour** [legomushroom/mojs#193]
In the [homepage](http://mojs.io), the sample code is missing a comma:
```
var burst = new Burst({
    radius:   { 15: 50 }, // <--
    children: {
      fill: [ 'deeppink', 'cyan', 'orange' ],
    }
});
```

Also, the tutorials are excellent, but it would be nice if they could be broken down into smaller sub-sections, because currently each of them is a tad bit too long. Finally, while in-depth tutorials are absolutely helpful, an [animejs](http://animejs.com/documentation/) style documentation could also be helpful for people who just want to glance over what code does what.

I'm definitely willing to help out with fixing those issues and writing docs. I just can't find it here. It might be a good idea to allow less-technical people to contribute to this awesome project?

**Comment by xavierfoucrier** [comment]
Hi @donfour,

May be you should post your issue on this website repository: https://github.com/legomushroom/mojs-website/issues.

Best regards :wink:

**Comment by donfour** [comment]
Opps thanks!
