### ISSUE TITLE
Don't restart animation on click

### ISSUE THREAD

**Issue by dipiana** [legomushroom/mojs#199]
Is there a way to start multiple animations via click?
I only found examples where the animation always restarted on every click (animation did not finish).

Thanks a lot!

**Comment by dipiana** [comment]
Hi @xavierfoucrier ,

Thanks for your response.
Let's take one of the official demos: https://codepen.io/sol0mka/full/03e9d8f2fbf886aa1505c61c81d782a0
When I click somewhere, the animation starts. Let consider it a "firework".
Everytime I click, a new "explosion" is triggered.
I now want that animation to finish, even when I trigger it again before it is finished.
Right now it stops the first animation/restarts the animation when I click before the first animation is done.

Cheers

**Comment by xavierfoucrier** [comment]
Oh ok I see,

You just need to **create an object every time** your click is fired, and just `play()` it like this:

```
document.querySelector('body').addEventListener('click', function(e) {
  new mojs.Shape({
    left: e.clientX,
    top: e.clientY,
    radius: { 0 : 'rand(50, 100)' },
    fill: 'transparent',
    stroke: '#fff',
    strokeWidth: { 10 : 0 },
    opacity: { 0.8 : 0 },
    duration: 700,
    onComplete: function() {
      this.el.parentNode.removeChild(this.el); // clean the DOM
    }
  }).play();
});
```

Don't forget to remove the child element, if you don't need it after animation, to **properly clean the DOM**.

Hope this help! :+1:

**Comment by dipiana** [comment]
Thanks - could make it work when I copy the options for the shape directly there.
As soon as I try to define the object outside of the event listener, I have to wait until the animation is done to restart it again. What am I doing wrong?

https://codepen.io/clmsvie/pen/pxWOYo

Thanks a lot!

**Comment by xavierfoucrier** [comment]
It's because you are using the `tune()` method: **this moved the object instantly** to another x/y coordinates.

So when the click event is fired, the current `Burst` will be moved to the new position and another animation will be generated and played, even if your current animation is not finished.

To prevent this from happening, you need to **create another object** in your click event: both object animations will be played in parallel.

 :wink:

**Comment by dipiana** [comment]
Ah, got it! Thanks! :)

**Comment by xavierfoucrier** [comment]
You are welcome!

Don't forget to **close the issue**: this will help reduce the number of issues that stays open on this repository.

Thanks! :wink:
