### ISSUE TITLE
What are the differences between this and famous engine?

### ISSUE THREAD

**Issue by roblav96** [legomushroom/mojs#20]
Just a little quickie here.

I'm currently using
http://famous.org/
as my primary UI framework.

What are the differences here between the two?

**Comment by roblav96** [comment]
Also the links on your sidebar/menu on the website are not clickable :X

**Comment by legomushroom** [comment]
@roblav96 sorry for long reply. Links on the sidebar were disabled because there was only one tutorial available. Please refer to this issue https://github.com/legomushroom/mojs/issues/31 .
