### ISSUE TITLE
Your website has been hijacked by a flash player spam

### ISSUE THREAD

**Issue by joniler** [legomushroom/mojs#205]
Your website is redirecting to a plash player virus installer. You should probably get your domain back... That or remove the links from your GitHub if you intend to abandon the domain.

**Comment by joniler** [comment]
Closing issue due to previously opened similar issue that I was unaware of! 🤪

**Comment by peterennisrda** [comment]
@xavierfoucrier

Considering the tardiness of @legomushroom and Microsoft
regarding a smooth transition, maybe add an issue that will not be closed.

e.g.

MOJS is Dead! LONG LIVE MOJS-CONTRIB!!!

Please review this ticket https://github.com/legomushroom/mojs/issues/201

The new repo is here:  ... etc. etc. yadda yadda
