### ISSUE TITLE
Please fix the documentation website!

### ISSUE THREAD

**Issue by roblav96** [legomushroom/mojs#21]
I click tutorials and all I get is easing path and nothing else is clickable on the side.

**IM DYING TO PLAY WITH DISSS!!!**

```
"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.80 Safari/537.36"
```
<img width="360" alt="screen shot 2015-12-11 at 7 59 16 am" src="https://cloud.githubusercontent.com/assets/1457327/11744302/1d9540ee-9fdd-11e5-9919-ef42558d120f.png">

**Comment by legomushroom** [comment]
@roblav96 please search thru issues before opening an issue. See https://github.com/legomushroom/mojs/issues/13 .
