### ISSUE TITLE
How to start from middle of timeline?

### ISSUE THREAD

**Issue by oxyflour** [legomushroom/mojs#22]
Hello! I'm trying to build a simple editor for this cool library and have made some progress (try [this link](http://lab.ofr.me/lemojs/) if you're interested). At present I'm faced with a problem: how can I start the timeline from middle? I have looked into the code and found ```Timeline.prototype.start(time)```, but it seems not working at all :(

**Comment by legomushroom** [comment]
Hey @oxyflour!

You are building the awesome tool! I had plans to build something like this but was busy with actual library code. I think we should collaborate with you on this. I deeply appreciate the amount of time and effort you've spent, luck of documentation makes it harder for you I believe. Also I'd like to discuss some concepts about the tool and how I see it. I'll invite you to `Slack` room for this, if you don't mind. 

`re: your question`
The current `master` version doesn't support that, I'm finished the version that support that in `dev` branch after few more tests I'll release it to `master`.
You can do something like :
```javascript
  timeline.play( 2000  ); // play form 2000 ms
  // or
  timeline.setProgress( .2 ).play();
```

Hope it helps, looking forward to see you in slack room. `Cheers!`

**Comment by oxyflour** [comment]
@legomushroom Glad that my work is helpful to the community. As you see the editor is still at an early stage of development and I do think it would become awesome with your help!

ps: Sorry that I didn't notice the ```dev``` branch before posting this issue. Although there are no complete documents yet, your codes are clean and easy to understand ;)

**Comment by legomushroom** [comment]
@oxyflour great. Did you receive my `Slack` invitation?

**Comment by legomushroom** [comment]
@oxyflour oh yeah, `dev` version should be much easier to understand all `public` methods are on top, not prefixed with `_` and covered by comments. Anyways please don't hesitate to ask me anything, to make sure we are on the same page.

**Comment by upq** [comment]
@oxyflour I would like you to help you out too, I'v been thinking about such thing for long time and I think there is no excuse not to get involved now, I took a look at your code, unfortunately I'm an angular man I'm not into react, but I'm an artist I can help in aesthetics, identity, UX, and design, let me know if you need anything.
@legomushroom great work , and If I can help also let me know.

**Comment by legomushroom** [comment]
@upq great! please should me you email

**Comment by legomushroom** [comment]
@upq legomushroom@gmail.com

**Comment by upq** [comment]
@legomushroom Done!

**Comment by legomushroom** [comment]
Hi, guys! Just merged the `dev` branch into the `master` and made the new `release`. Woot Woot. See the [Tweens API](https://github.com/legomushroom/mojs/blob/master/api/index.md#tweens)
