### ISSUE TITLE
[Question] Where to find the demo's code?

### ISSUE THREAD

**Issue by monapasan** [legomushroom/mojs#25]
It would be much appreciated,if you could say me, where i can find code of this demo : http://codepen.io/sol0mka/full/ogOYJj/  ? 
in Codepen it looks unreadable.

**Comment by legomushroom** [comment]
@monapasan here it is: https://github.com/legomushroom/mojs-demo-1 but with mojs v110, will update it shortly with the new version.

**Comment by monapasan** [comment]
@legomushroom  Nice! 
Thank you
