### ISSUE TITLE
Trying to use with jquery

### ISSUE THREAD

**Issue by Jordan4jc** [legomushroom/mojs#28]
I'm using Ember.js which is built on jQuery. I have what are called components which are basically just templates that represent a small piece of UI that gets rendered in multiple places.
Each of these components that renders gets a unique ID and in the code backing the component I have access to the individual components element via jQuery. However I've found trying to pass that to mojs seems to get me this error

    Uncaught TypeError: (this.o.parent || document.body).appendChild is not a function

I've tried to dereference to javascript using `.get(0)` but the problem is now that I get the animations only attaching to the first occurrence of my element I'm matching on.

My particular implementation of this library is using a small library created [here](http://tympanus.net/codrops/2016/02/23/icon-animations-powered-by-mo-js/?utm_source=designernews)

Which was using `document.querySelector` but I need to be a little more specific so I can attach these icon animations to each component so I can animate them individually.

**Comment by legomushroom** [comment]
Hey @Jordan4jc! Thanks for the alert!

Cloud you please make the issue sample somewhere on [codepen](http://codepen.io) or similar? Not sure I got the problem right. The error seems for that you are passing an object but not `HTMLNode` to `parent` option. jQuery's `.get(0)` will get `HTMLNode` for you so it solves the issue. 

Still not sure what do you want to achieve, a small `code sample` will help a lot.
Thanks!

**Comment by kmiyashiro** [comment]
@Jordan4jc try using https://api.jquery.com/toArray/ to get an array of elements in your selection. I would suggest building a mixin or helper to call the animation code directly from the components as well.

**Comment by legomushroom** [comment]
Hi @kmiyashiro! Thanks for the solution. I still don't get the issue and would deeply appreciate if you could make a code sample with it? Thanks!

**Comment by Jordan4jc** [comment]
I have plans to try to make a code sample to see if I can get the same effect, I'll also give the toArray a shot as right now I'm hacking it to make it work. @kmiyashiro I plan on making it a mixin or a component once I find the best way to put it all together. Probably as soon as mo.js docs get a bit more full.

**Comment by legomushroom** [comment]
@Jordan4jc thanks!

**Comment by BenevidesLecontes** [comment]
I have this issue too, what i want to do, is select all elements with some classes and animate all of them, instead of using pure js like (using like this, work great, for one element): 
<img width="850" alt="screen shot 2016-03-22 at 1 02 16 am" src="https://cloud.githubusercontent.com/assets/1839361/13941770/da419102-efc9-11e5-9dbe-c6088c264a83.png">

I would like to use:
<img width="811" alt="screen shot 2016-03-22 at 1 02 35 am" src="https://cloud.githubusercontent.com/assets/1839361/13941779/eae20492-efc9-11e5-9bc1-4b2a00cd979d.png"> 
But when i use the code above i get the same error as @Jordan4jc mentioned
<img width="528" alt="screen shot 2016-03-22 at 1 05 46 am" src="https://cloud.githubusercontent.com/assets/1839361/13941812/47ba4c92-efca-11e5-9723-c0782c3e3a84.png">

**Comment by TheSisb** [comment]
From that error, it seems like appendChild() is being called on some element.  My guess is that it is getting a DOM element, so you should look into wrapping it like this:
```js
$(this.o.parent || document.body).appendChild
```

**Comment by legomushroom** [comment]
The issue like that usually appears if you place the link to the lib inside the `head` tag.

The library adds it's modules to the `parent` option (`this.o.parent`) you have specified on module construction, if you haven't specify anything in `parent` option, it fallbacks to the `body`:
(`(this.o.parent || document.body).appendChild`). Thus it tries to access `body` that hasn't been yet initialised. If you move the `script` inside body tag (or better to the end of the `body` tag), it should solve the issue.

Hope it helps.

**Comment by BenevidesLecontes** [comment]
@legomushroom I have my scripts at the end of body tag and i have timeout as well. So, for me this isn't the solution. Thanks.

**Comment by legomushroom** [comment]
@BenevidesLecontes could you make an example on codepen?

**Comment by BenevidesLecontes** [comment]
@legomushroom take this plunker http://plnkr.co/edit/urqqKI?p=preview, click on resolveview link and test. You'll see icons animating, using pure js, uncomment the line using jquery and you'll see the error on the console. Thanks

**Comment by legomushroom** [comment]
@BenevidesLecontes thanks for the demo.
If you use ` var el11 = document.querySelectorAll('span.icobutton')[0]` - you take the first element in the search - `[0]`. So when you use `$`, take the first element too:
```javascript
var el11 = angular.element($('span.icobutton')[0]), el11span = angular.element($('i.fa-microphone')[0]);
```
This way no errors fire.

As I got it, you want both icons to work the same way?

**Comment by BenevidesLecontes** [comment]
Yes I want to select all the items and animate them all the same way. With your edited line, the error keep showing in the console and the icons don't work.

**Comment by legomushroom** [comment]
@BenevidesLecontes updated the plunker http://plnkr.co/edit/g2xz2g6OuP7ZG4rjXJKK?p=preview

**Comment by legomushroom** [comment]
@BenevidesLecontes pushed more updates. Right now it creates the animation sequence for each icon with `createAnimation` function. Note that the `parent` option expects `DOMNode` -- not `jQuery` wrapped element nor `NodeList`. The next `mojs` release that I will make shortly will allow you to easily reuse the same sequence multiple times.  Hope it helps.

**Comment by BenevidesLecontes** [comment]
@legomushroom Thanks for the help and thanks for this amazing library.
