### ISSUE TITLE
Mojs and require console error

### ISSUE THREAD

**Issue by wanbinkimoon** [legomushroom/mojs#29]
I'have tried to install `mojs` using `bower install mojs` and the console keep reporting 2 undefined functions: require and mojs. I tried to fix it installing via bower requirejs but the problem kept going on. Am I skipping any passage?

**Comment by legomushroom** [comment]
Hi @wanbinkimoon !

Thanks for the alert. Could you please post the entire log here, just tried to install it with `bower install mojs` and it worked fine.

Thanks!

**Comment by wanbinkimoon** [comment]
This is what the console respond with this error

```
Console 
mojs.js:5 Uncaught ReferenceError: require is not defined
main.js:3 Uncaught ReferenceError: mojs is not defined
```

you can find the whole test project in this repo https://github.com/wanbinkimoon/mojs-test.git

**Comment by legomushroom** [comment]
@wanbinkimoon pushed the fix to the `master`.

Meanwhile `Bower` updating package's version, please try to install `mojs` with `bower install https://github.com/legomushroom/mojs.git#master`

If it will ask a specific commit to use - that would be `3dfdc4ae03`.

**Comment by wanbinkimoon** [comment]
@legomushroom the problem is still there

**Comment by legomushroom** [comment]
@wanbinkimoon please change the link
`<script src="assets/vendors/mojs/lib/mojs.js" charset="utf-8"></script>`
to
`<script src="assets/vendors/mojs/build/mo.min.js" charset="utf-8"></script>`

**Comment by wanbinkimoon** [comment]
I did that

**Comment by legomushroom** [comment]
what do you pass as `parent' option?

**Comment by legomushroom** [comment]
sorry, wrong direction.

I got the issue now, please move your scripts inside `body` tag (better to the very bottom of it). `mojs` adds modules to the `document.body` which is not yet inited if you will link it in the `head` thus you got the error. You will have the same issue with `#mo-shape` tag since you are trying to use it before it was declared.

Hope it helps.

**Comment by wanbinkimoon** [comment]
It helped, error fixed. Thanks

**Comment by legomushroom** [comment]
Welcome and thanks for the alert!
