### ISSUE TITLE
animation for multiple items

### ISSUE THREAD

**Issue by NetGon** [legomushroom/mojs#36]
I need your help. To apply animation to multiple elements with a single class of "my-button"? Now this only works for a single button.
Replacement **querySelector** on **querySelectorAll** not solve the problem, the script becomes not working
Demo: http://codepen.io/ey_intuitive/pen/NxQdyY

Thank you!

**Comment by legomushroom** [comment]
@NetGon hey, sorry for the delay. In the `mojs` version you are using you need to add the effect to each button, please refer to this [pen](http://codepen.io/sol0mka/pen/rLyLRa?editors=0010). In the new version which I will release very soon, you can reuse the same effect for every button - so you will have to initialise it once. 

Hope it helps,
Cheers!
