### ISSUE TITLE
Animate along a path

### ISSUE THREAD

**Issue by karneaud** [legomushroom/mojs#37]
I have the following [fiddle ](https://jsfiddle.net/karneaud/c1vz4smr/25/) and I'm trying to figure out how to use **MotionPath** to animate something along a path 

But I'm puzzled as to how to set the _path_ property is it the path element or an array of some sort?

I keep getting this error

> [Error] TypeError: undefined is not an object (evaluating 'this.path.getPointAtLength')
	setProgress (mo.js:2056)
	createTween (mo.js:2041)
	VanillaRunOnDomReady (_display:100)
	(anonymous function) (_display:109)

**Comment by legomushroom** [comment]
@karneaud hey! The Motion Path module is for html elements currently. THere is how you can do it - https://jsfiddle.net/gvzekze5/ . `path` can be a `selector` of the path or `PathElement` (DOM node) or `d` data as you did https://jsfiddle.net/gvzekze5/1/ . Unfortunately the api of motion path is not stable and will be changed shortly to fit other modules, fortunately you will have good `API` reference at that point and probably exhausted tutorial. Hope it helps.

**Comment by karneaud** [comment]
>  Unfortunately the api of motion path is not stable and will be changed shortly to fit other modules

CRAP! I want to use your library and more specifically the MotionPath module for a production project! Is it worth using?

**Comment by legomushroom** [comment]
Well you can use it in production - the library is well tested so it is consistent in all browsers down to `IE9` and `FF4`. The functionality you are looking for is there also. Just keep your eyes open - after few releases I will have to add few tweaks to the module. So the `run` method will be suppressed by `play` one, some new properties will be added and so on. I don't think it will be hard to upgrade your code if you will want to migrate to newer `mojs` version in the future.
