### ISSUE TITLE
pathStart and pathEnd

### ISSUE THREAD

**Issue by karneaud** [legomushroom/mojs#38]
What are the values of _pathStart_ and _pathEnd_ in relation to the motion path? a percentage? a segment? i see it has a clam range between 1 and 0

**Comment by legomushroom** [comment]
Those are if you want to start the animation for instance from `half length` of the path and end at `3/4 of the length` thus you can set the params in `[0..1]` range - from `0` to the `full length(1)`. I hope it makes sense.

**Comment by legomushroom** [comment]
so it's like:

```javascript
  //.. 
  pathStart: .5 // start from half length of the path
  pathEndL .75 // end at 3/4 of the path
 //...
```

**Comment by karneaud** [comment]
Yeah I figured as much. Its a pretty vague approach....why couldn't we use a specific x,y?

**Comment by legomushroom** [comment]
Hm, specific coordinates? I think because a path can have multiple equal coordinates. How do you see it exactly?

**Comment by karneaud** [comment]
@legomushroom well i don't think the software should be faulted because of such anomalies but the I think people might want motion to be of an x,y sort of characteristic. 

Currently for my project I need to move a an element to specific coords along a path at intervals. Currently with your project I can't really use motion path i have to use a combination of tweens....which is not bad because your framework is awesome it would be nice though if the  motion path had this built in...It practically has everything we need  the path a way to get the points why not run(pathStart: Point, pathEnd: Point)....which at first glance i actually though it was the accepted value type

**Comment by karneaud** [comment]
@legomushroom 

I refer to my latest [fiddle](https://jsfiddle.net/karneaud/gvzekze5/37/) I'm trying to extract a segment from the path between two xy points. Since I don't have that option i need to now find the length at each point then try to convert the length into pathStart and pathEnd values?
