### ISSUE TITLE
onComplete sometimes not running

### ISSUE THREAD

**Issue by Errvald** [legomushroom/mojs#39]
`onComplete` is not being called half the time. I'm calling it from the last `Tween` in the timeline.

**Comment by legomushroom** [comment]
hey, sorry about that. This will be fixed in the new release, that I will put public in couple days.

**Comment by Errvald** [comment]
Thanks, awesome library btw can't wait for the full documentation.

**Comment by legomushroom** [comment]
thanks! working on it
