### ISSUE TITLE
Run animation inside an existing svg

### ISSUE THREAD

**Issue by kandebonfim** [legomushroom/mojs#47]
There is any way to set a container where `mojs` should run the animation?

**Comment by legomushroom** [comment]
Hey! There was such option but I've removed it. You can set an html container with `parent` Option right now. If you will provide me with more info on want you want to achieve I probably will be able to find the right way for you.

**Comment by legomushroom** [comment]
Actually I'm considering to add few renderers - `svg`, `canvas` and `webgl`. This will allow you to choose the technology you want and specify the rendering container.

**Comment by kandebonfim** [comment]
Thanks for helping me!

Here is what I want to do. Animate this illustrated graph inside the screen. 👍  

http://codepen.io/kandebonfim/pen/OXENgJ

**Comment by legomushroom** [comment]
You can wrap the svg with a dive and pass it as parent to modules. Should work.

**Comment by legomushroom** [comment]
http://codepen.io/sol0mka/pen/qNKNLb

**Comment by kandebonfim** [comment]
Oh, sorry for not answering. This will work for me. Thanks!!

**Comment by legomushroom** [comment]
@kandebonfim np, happy to help!
