### ISSUE TITLE
Use with Webpack

### ISSUE THREAD

**Issue by roundrobin** [legomushroom/mojs#50]
I am trying to setup mo.js in my webpack configuration.

installing it via `npm install mo-js --save` and then importing it via `import mojs from 'mo-js'` doesn't work.

Any tips how to set it up? Is the lib actually Es6 module compatible?

**Comment by TheSisb** [comment]
`import mojs from 'mojs'` worked for me

**Comment by roundrobin** [comment]
`mojs` is a different library when loaded via NPM
https://www.npmjs.com/package/mojs

how are you loading it?

**Comment by TheSisb** [comment]
I didn't test it in-depth, but it returned an object:
`npm install mo-js`
then
`import mojs from 'mojs';`

**Comment by TheSisb** [comment]
Looks like I do.  Sorry!

**Comment by legomushroom** [comment]
@roundrobin hi, sorry about that! I've just rechecked and yes we have the problem with `es2015` modules and even with `require` statements. I've solved the issue but need a drip more tests to ensure it works everywhere. Will try to push the `hotfix` to the `master` branch tomorrow.

Thank you so much for heads up and sorry again. Cheers

**Comment by roundrobin** [comment]
Awesome @legomushroom That would be amazing. I am happy to test it then #GoEs2015

**Comment by legomushroom** [comment]
@roundrobin just released the `0.265.8` version that should fix the issue. Please let me now if doesn't work for you.

**Comment by roundrobin** [comment]
Thanks @legomushroom it works for me! Although only with `require('mo-js')` syntax, when using import statement, it doesnt work.
 
Thanks for the fast fix 💯

**Comment by legomushroom** [comment]
@roundrobin hm it worked for me with `import` just fine. Could you check this project in the attached archive and confirm if it works for you? [Archive.zip](https://github.com/legomushroom/mojs/files/412275/Archive.zip)

**Comment by hyperbrave** [comment]
I keep getting mojs is undefined errors thrown from helpers, for example:

mo.js:5370   Uncaught ReferenceError: mojs is not defined
```javascript
Helpers.prototype.error = function() {
  if (mojs.isDebug === false) {
    return;
  }
  return console.error.apply(console, this.prepareForLog(arguments));
};
```

**Comment by legomushroom** [comment]
@hyperbrave ah that's bad. was rushing to release the fix. You are using the latest release, right?

**Comment by hyperbrave** [comment]
@legomushroom  

"mo-js": "^0.265.8",

The reference error is definitely not always occurring, only a few times.  I encountered it initially  while trying to copypasta this example.   http://codepen.io/sol0mka/pen/pbRejJ

It is thrown always when using an invalid value in burst children options.

```javascript
new mojs.Burst({
  children: {
     // oops 
    shape: ["triangle"],
  }
})
```

**Comment by legomushroom** [comment]
@hyperbrave thanks! Please use the version `0.265.6` for now, I'll try to fix that asap.

**Comment by legomushroom** [comment]
@hyperbrave made `0.265.9` release with the fix, if you use `jsdelivr` / `bower` to install the library might need some time to show up on their website. Hope it helps!

**Comment by hyperbrave** [comment]
@legomushroom thanks!   no mojs reference error thrown by helpers, and a useful log message!

mo.js:5376 mo·js no "triangle" shape available yet, please choose from this list: ["circle", "line", "zigzag", "rect", "polygon", "cross", "equal", "curve"]

**Comment by legomushroom** [comment]
@hyperbrave happy to help! 😊

**Comment by SuneethaYamani** [comment]
"mo-js": "^0.288.2" version I am facing same issue

**Comment by xavierfoucrier** [comment]
Hi @SuneethaYamani,

You should now use the lastest release from the NPM org.:
`import mojs from '@mojs/core'`

Check the official documentation at https://mojs.github.io/tutorials/getting-started.html#setup-mo-js-in-your-project.

:wink:
