### ISSUE TITLE
Resetting a shape and removing 'then's?

### ISSUE THREAD

**Issue by JoeDMitchell** [legomushroom/mojs#51]
So I have an animation run, a couple of shapes are created and 'then' added to them to create a multistep animation. On a click I then have the same shapes animate out, again using 'then' (I'm just adding a 'then' to them, then running play() instead of replay() so it goes from the last point. 

At this point, I want to restart the animation, just doing the first half. However, when I restart it plays the whole thing including the animate out. I understand why it does this, because I'm gradually making a chained animation. So my current solution is to remake the shapes and start again. However this seems ridiculous as I'm left with shapes in the DOM and you're getting more and more shapes. 

Is there a better way I can just run the first part of the animation again? Am I going about this wrong with my animate out? 

Thanks in advance.

**Comment by legomushroom** [comment]
@JoeDMitchell hi, thanks for starting the discussion. Sometimes it is hard to understand an issue by reading just generalized text so it is always a good idea to make a simple live code sample, it would be so much helpful to understand the pitfalls you are struggling with.

Currently, there is no public method to remove a bunch of `then` shapes in the `APIs` but I can add it as it might be useful. For now, you can probably hook into an `onComplete` callback on some of the `then` blocks to pause the tween. [codepen demo](http://codepen.io/sol0mka/pen/VjqbvZ?editors=0011)

If you will need to continue adding the `then` calls afterwards, you can just use the `setProgress` method to start just before the last `then` call. [codepen demo](http://codepen.io/sol0mka/pen/QEzvym?editors=0011)

Hope it helps, please let me know if it works for you. Would also highly appreciate if you will share your thoughts on how to optimize it. Maybe relative `labels` can smoothen the experience for you? Or the ability to run the animation in some `time period`, like `play( 500, 1600 )`?
