### ISSUE TITLE
Problem with multiple button in a table

### ISSUE THREAD

**Issue by jcorreia** [legomushroom/mojs#53]
Hi,
 I have a table with multiple buttons. Everytime I click on a button, there is an burst animation.

This is really strange, but If I click from in each button from top to bottom, all the buttons work.
If I click from the bottom to the top, some of the top button start to lose the ability to click. If you hover with the mouse you will understand.

I´ve built a codepen to prove this here: https://codepen.io/jcorreia/pen/xOZPbo
If you wish I can build a download demo.

I think it´s mo.js related because i you comment line 20 in the js panel:

```
    //play animation
   moAnimationSuccess($(clickedElement));

```
The buttons

 behave normally.

Can you check this ?
Thanks :)

**Comment by legomushroom** [comment]
Hi, thanks for the issue!

Just add `isShowEnd: false` to your `bursts`, so their markup will be hidden completely after animation ends, so it won't inеrfere with the mouse pointer. [codepen demo](https://codepen.io/sol0mka/pen/akxVyb)

Cheers!

**Comment by jcorreia** [comment]
wow..you are fast, and that solved my problem :)

Another issue I noticed, is that after some button clicks, it seems the animation are starting to becoming "heavy" and with some delays..but it could be my browser  ...

Thanks !!

**Comment by legomushroom** [comment]
@jcorreia welcome! That's because you create new instances of the `bursts` every time user clicks the button, so you are ending up with lots of modules and playing all of them at once afterwards.

You can use `replay` method instead:

```javascript
  // create timeline and bursts for every button
  var timeline = new mojs.Timeline;
  timline.add(  new mojs.Burst({ ...opts }),  new mojs.Burst({ ...opts }) );

// replay timeline on every click event
 $('#js-button').on( 'click', function () {
   timeline.replay();
  } );
```

This will ensure you don't create redundant modules on each click event.

You can even use just one pair of the bursts for all buttons with help of `tune` method which will adjust position of the bursts::

```javascript
  // create just one timeline and bursts pair
  var timeline = new mojs.Timeline;
  var burst1 = new mojs.Burst({ ...opts });
  var burst2 = new mojs.Burst({ ...opts });
  timline.add(  burst1,  burst1 );

 $('.button').on( 'click', function (e) {
   burst1.tune({  x: e.pageX, y: e.pageY });
   burst2.tune({  x: e.pageX, y: e.pageY });
   timeline.replay();
  } );
```
But this way, don't specify `parent` for your bursts - it should be appened to `body` .

**Comment by jcorreia** [comment]
Hi,
Thanks for the code to optimize this.
I dont think your first option would work, because I´m already using replay, and if it was done like you show I wouldn´t have any way to pass the parent to the burst options...unless theres something I´m missing :)

I´ve tried your second option and it works, but the burst are not on the buttons. They are in the right lower corner.
I´ve made a codepen to show this: https://codepen.io/jcorreia/pen/GqaqXE

thanks :)

**Comment by legomushroom** [comment]
Hi, that's because your bursts are in the center by default and you defining the shift with the `x`/`y` properties, so your animation is in the `center + pageX` position. You can fix that by setting `left` and `top` to `0` on bursts. [codepen demo](https://codepen.io/sol0mka/pen/KrLmpz)

**Comment by jcorreia** [comment]
Thanks :)
That worked out and indeed it is much more faster now.
