### ISSUE TITLE
website display issues: ReferenceError: children is not defined

### ISSUE THREAD

**Issue by timoxley** [legomushroom/mojs#54]
Something not right. Intermittent. Once working, always works. Cache/load order issues perhaps.

1. Navigate to site
2. Click on tutorials

#### Chrome Version 54.0.2837.0 dev (64-bit) OS X

![image](https://cloud.githubusercontent.com/assets/43438/17933102/2cbf33a6-6a56-11e6-8106-4a2bb36e9d24.png)

![screen shot 2016-08-24 at 11 59 19 pm](https://cloud.githubusercontent.com/assets/43438/17933795/c8ca3df2-6a58-11e6-802e-ac5de7de4902.png)

#### Firefox 48.0.1

<img width="1788" alt="screen shot 2016-08-25 at 12 13 03 am" src="https://cloud.githubusercontent.com/assets/43438/17933796/c8cd00e6-6a58-11e6-97f2-044f0ddf8141.png">

**Comment by legomushroom** [comment]
Hi, Tim! Thanks for the heads up!

Strange it didn't break in previous versions of the browsers. Will fix in 10 minutes.

**Comment by legomushroom** [comment]
@timoxley fixed. Thanks again for the alert and sorry for the inconvenience.

Cheers!
