### ISSUE TITLE
Animate one at a time without using then call

### ISSUE THREAD

**Issue by anshap1719** [legomushroom/mojs#59]
**Hello, this is more of a 'help required' rather than an issue.**

Suppose I have added multiple path objects under a single shape. I was wondering if there is any way that I could animate them one at a time without using separate then calls for each path because I have a big name to animate...

**Comment by legomushroom** [comment]
Hi Anshul!

Thanks for the question! Not sure I'm 100% understood you. You are using `custom shapes` and want to animate them? Or you are using `motion path` for shapes? A simple code snippet would help a lot. Cheers!

**Comment by anshap1719** [comment]
Give me just another day... I'll upload a code snippet soon!

**Comment by legomushroom** [comment]
sure, take your time :)

**Comment by anshap1719** [comment]
Take the following code for example... It's from the tutorials of mojs itself :

`class Heart extends mojs.CustomShape {
  getShape () {
      return '<path d="M79.8226133,31.1716767 C71.2668462,22.7128894 57.4418472,22.7128894 48.8860801,31.1716767 L45.1254217,34.910784 C43.9939916,36.0098876 42.1837033,36.0206631 41.0522732,34.889233 L41.0522732,34.889233 L37.3023903,31.1716767 C28.7789498,22.7128894 14.9323997,22.7128894 6.40895921,31.1716767 C-2.13603238,39.6520152 -2.13603238,53.3800345 6.40895921,61.8280463 L25.686374,80.9653793 C25.686374,80.9761548 25.6971496,80.9761548 25.6971496,80.9869304 L37.2916148,92.4844159 C40.4919458,95.6739714 45.6857491,95.6739714 48.8860801,92.4844159 L60.4913209,80.9869304 C60.4913209,80.9869304 60.4913209,80.9761548 60.5020964,80.9761548 L79.8226133,61.8280463 C88.3352783,53.3800345 88.3352783,39.6520152 79.8226133,31.1716767 L79.8226133,31.1716767 Z"></path>' +
             '<path stroke="#50E3C2" d="M87.2293862,20.3305554 C81.6681375,14.8323436 72.6818882,14.8323436 67.1206395,20.3305554 L64.6762116,22.7609751 C63.940782,23.4753925 62.7640947,23.4823966 62.0286651,22.746967 L62.0286651,22.746967 L59.5912412,20.3305554 C54.0510049,14.8323436 45.0507473,14.8323436 39.510511,20.3305554 C33.9562665,25.8427754 33.9562665,34.7659879 39.510511,40.2571956 L52.0408306,52.6964621 C52.0408306,52.7034662 52.0478347,52.7034662 52.0478347,52.7104703 L59.5842371,60.1838358 C61.6644523,62.2570469 65.0404244,62.2570469 67.1206395,60.1838358 L74.6640461,52.7104703 C74.6640461,52.7104703 74.6640461,52.7034662 74.6710502,52.7034662 L87.2293862,40.2571956 C92.7626184,34.7659879 92.7626184,25.8427754 87.2293862,20.3305554 L87.2293862,20.3305554 Z"></path>' +
             '<path d="M97.1269756,7.85484074 C93.2768804,4.04838642 87.0556308,4.04838642 83.2055356,7.85484074 L81.5132393,9.53743902 C81.0040958,10.0320356 80.1894661,10.0368846 79.6803225,9.52774105 L79.6803225,9.52774105 L77.9928752,7.85484074 C74.157327,4.04838642 67.9263795,4.04838642 64.0908312,7.85484074 C60.245585,11.670993 60.245585,17.8486017 64.0908312,21.6502071 L72.7656679,30.2620069 C72.7656679,30.2668559 72.7705169,30.2668559 72.7705169,30.2717049 L77.9880262,35.4455734 C79.4281752,36.8808733 81.7653866,36.8808733 83.2055356,35.4455734 L88.427894,30.2717049 C88.427894,30.2717049 88.427894,30.2668559 88.4327429,30.2668559 L97.1269756,21.6502071 C100.957675,17.8486017 100.957675,11.670993 97.1269756,7.85484074 L97.1269756,7.85484074 Z"></path>';
  }
  getLength () { return 200; } // optional
}
mojs.addShape( 'heart', Heart ); // passing name and Bubble class

/* USE CUSTOM SHAPE */
// now it is available on mojs.Shape constructor as usual
const heart = new mojs.Shape({
  shape:    'heart',
  fill:     'none',
  stroke:   { 'white' : 'deeppink' },
  scale:    { 0 : 1 },
  strokeWidth: { 50 : 0 },
  y:         -20,
  duration:  1000,
});`

All I want is the three paths (in this case the three hearts) should be animated one at a time without chaining them with the then call... i.e. is there a direct option for that?

**Comment by legomushroom** [comment]
Hi, Anshul! Thanks for the snippet!

So you have 3 shapes inside your module, and want to animate them one by one? It is not possible because for `mojs` that's just a complex shape that consists of 3 `<path>` elements.

If you want to animate one shape at time - you need to create 3 different modules with more simple shapes, something like that: [codepen](http://codepen.io/sol0mka/pen/1190196754e9809b34e250a0c2bc4751?editors=0010). You can even make it more concise with `Stagger` module: [codepen] (http://codepen.io/sol0mka/pen/b911781ec95941ef5a6ea20ca36c0d63).

Hope it helps!

**Comment by anshap1719** [comment]
Hello,

Thanks for your reply... That closes the issue then :smile:
