### ISSUE TITLE
Bower main

### ISSUE THREAD

**Issue by TrySound** [legomushroom/mojs#6]
As you see in [bower spec](https://github.com/bower/bower.json-spec#main) main field must contain non-minified versions of files. And you can do not use version field, caz it's updates with git tags.

**Comment by legomushroom** [comment]
@TrySound hey, thanks for your note!

The same truth for `npm`. Will fix in the next release.

*Cheers!*

**Comment by TrySound** [comment]
@legomushroom About `.min`, yes. Version field in package.json must be :)
