### ISSUE TITLE
Animate existing SVG symbols

### ISSUE THREAD

**Issue by rootion** [legomushroom/mojs#60]
Thanks for this wonderful library! It's so much fun to work with it.

Would it be possible to create a custom shape that uses a symbol already included in the document?
Let's say I am loading all my SVG in symbols that I want to reuse later, something like:

```
<svg xmlns="http://www.w3.org/2000/svg"> 
<symbol id="icon" viewBox="0 0 10 10">
<path d="M5 10c-2.8 0-5-2.2-5-5s2.2-5 5-5 5 2.2 5 5-2.2 5-5 5"/>
</symbol>
</svg>
```

which I am later using as

```
<svg class="icon" >
  <use xlink:href="#icon" x="0" y="0"></use>
</svg>
```

Would it be possible to use the `use xlink:href="#icon"` in the creation of the custom shape?

**Comment by legomushroom** [comment]
Hi @rootion! Thanks for opening this issue!

Yep, it will work as expected - [codepen example](http://codepen.io/sol0mka/pen/vXKvmm?editors=1010).

Hope it helps!

**Comment by rootion** [comment]
Wow, this is awesome!! 
Thanks a lot for the example!
