### ISSUE TITLE
Animating/Morphing custom path

### ISSUE THREAD

**Issue by Errvald** [legomushroom/mojs#61]
Will Moj in the future have the ability to animate svg paths? Similar to <animate or Snap.svg.

**Comment by legomushroom** [comment]
@Errvald hi, thanks for the issue! What do you mean under animate a path? Animate an object along a path, or animate path's `strokeDash` properties?

**Comment by Errvald** [comment]
I have this svg icon:
![Icon](https://s16.postimg.org/mvkw7jnxx/email_icon.png)

I'm trying to animate the opening of the envelope, so far I've tried with css to `rotate` or `scale`, it works but at certain angles the stroke looks flat and can cause flickering.

Morphing doesn't affect the thickness of the stroke.

**Comment by legomushroom** [comment]
@Errvald makes sense, thanks, so you want to add morph. Might be a good feature to add next, let me ponder about it. For this simple case, you have few variants with `mojs`:

- use shape `zigzag` and `then` chain to flip the color [codepen example](http://codepen.io/sol0mka/pen/75405c9237590eefda8c1394c5279b5f?editors=0010)
- hook right into the `path coordinates of your path` [codepen example](http://codepen.io/sol0mka/pen/2a21f78cca962db2d5b6ad76e6b42fa1?editors=0010)

Hope it helps!
