### ISSUE TITLE
Bad legibility on 1x displays

### ISSUE THREAD

**Issue by hpohlmeyer** [legomushroom/mojs#8]
The description text of the features looks really bad on 1x displays:

![bildschirmfoto 2015-11-19 um 17 27 06](https://cloud.githubusercontent.com/assets/6564077/11276622/17dcb494-8ee3-11e5-8aa4-cafe00304cd7.png)

OS X 10.11.1
Safari 9.0.1

**Comment by legomushroom** [comment]
@hpohlmeyer you are right. Will fix shortly, thanks

**Comment by hpohlmeyer** [comment]
@legomushroom You are fast! :D Nice site besides that.

**Comment by legomushroom** [comment]
@hpohlmeyer didn't fix it yet, so not that fast :)

**Comment by legomushroom** [comment]
@hpohlmeyer pushed the style fixes, please check

**Comment by hpohlmeyer** [comment]
Ok, back on a 1x screen. Clearly better now.

**Comment by legomushroom** [comment]
@hpohlmeyer thanks for the heads up
