### ISSUE TITLE
Allow usage of "points" to create Custom shape in place of path

### ISSUE THREAD

**Issue by curranlipsett** [legomushroom/mojs#80]
Would it be possible to allow custom shapes to be created and added to mojs using svg points instead of the svg path? 

If I receive an svg file with this:
`points="0 0 0 13.51 19.9 31.51 0 49.5 0 63 34.83 31.51 0 0"`

Is there much I can do to add that shape to mojs without manually recreating it using a path?

Thanks for looking into this, mojs has been awesome to work with so far!

**Comment by legomushroom** [comment]
Hi @curranlipsett! Thanks for the issue!

Looks like this is `polygon` coordinates, so just use `<polygon>` tag instead of `<path />`:

```javascript
class CustomShape extends mojs.CustomShape {
  getShape () { return '<polygon points="0 0 0 13.51 19.9 31.51 0 49.5 0 63 34.83 31.51 0 0" />' }
}
```

Please, let me know if it works for you.

**Comment by curranlipsett** [comment]
@legomushroom WOW! Thanks for the quick reply, that's incredible :)

You're absolutely right, that works perfectly. 

I also found a way to convert points to path (http://stackoverflow.com/questions/16245712/convert-svg-polygon-points-to-path) that also seems to work, though the output needs a little formatting.

I appreciate your quick reply and great answer, thanks!

**Comment by legomushroom** [comment]
@curranlipsett you are welcome! Custom shape can hold basically any tags, so no need to always convert them to paths.

Cheers!
