### ISSUE TITLE
Basic translate animation

### ISSUE THREAD

**Issue by Madebym** [legomushroom/mojs#81]
Sorry for spamming with such basic things, but maybe it also helps some JS newbies like me.

How should I write some basic element translate animation? I scanned through the available docs, do I need to do it like in the HTML module?

In GSAP I would do something like this:

    var translate_me = $('.element');
    TweenMax.fromTo(translate_me, 1.8, {
        x: -200,
        opacity: 0
     },

     {
        x: 0,
        opacity: 1,
        delay: 0.8,
        ease: Power3.easeOut
    }
);

This will translate on the x-axis from -200px to 0, along with opacity from 0 to 1.
What is the mo.js equivalent of that snippet?

**Comment by sdras** [comment]
Hi @Madebym! 

You would put it in an object if you're trying to tween it like this: 
http://codepen.io/sdras/pen/b7e532e672976d404100d34f6239f3ca

```
var bubble = new mojs.Shape({
  x:        {0 : 200},
  opacity:  {0 : 1},
  delay:    800,
  easing:   'expo.out',
  duration: 3000
});
```

but keep in mind that that's if you're creating a shape. If you're taking something existing and animating that, you would do something like this: 
http://codepen.io/sdras/pen/737dc7c11943fa41359e8e772a957a8d

```
var thingtoselect = document.querySelector('.circ');
new mojs.Tween({
  duration:    4000,
  delay:         800,
  onUpdate: function (progress) {
   var updateProgress = mojs.easing.expo.out(progress);
    thingtoselect.style.transform = 'translateX(' + 200*updateProgress + 'px)';
    thingtoselect.style.opacity = updateProgress;
  }
}).play();
```

A couple of gotchas if you're used to GSAP: 

- GSAP uses seconds, so a delay would be 0.8 seconds in GSAP and mo.js uses milliseconds and  would be 800
- GSAP only alters existing things, while mo.js lets you drum up the shapes to work with if you'd like working that way. If not, you're basically changing up the style elements and plotting them along the ease progress
- GSAP and mo.js eases are slightly different. Check out the mo.js eases here: https://github.com/legomushroom/mojs/blob/master/api/easing/base-functions.md. Expo is the same ease function as Power4.

Hope that helps!

**Comment by legomushroom** [comment]
Hi, Mirko!

You can just use `Html` module for that:
```javascript
new mojs.Html({
  el:        '.element',     // element to apply the animation to
  x:         { '-200' : 0 }, // from -200 to 0
  opacity:   { 0 : 1 },      // from 0 to 1
  delay:     800,            // milliseconds = 0.8 seconds
  easing:   'expo.out'       // mojs uses common standart easing functions
}).play();                   // play the animation
```
There is [codepen demo](http://codepen.io/sol0mka/pen/bBvGVW?editors=0010).

Here is the reference for all the properties and methods for the [Html module](https://github.com/legomushroom/mojs/blob/master/api/html.md).

Another nice thing about this module is that it can have `delay`, `duration`, `callbacks` and any other tween values in `delta` properties, like:

```javascript
new mojs.Html({
  el:        '.element',     
  x:         { '-200' : 0, duration: 2000, easing: 'cubic.out' }, // `x` delta has it's own `duration` and `easing`
  opacity:   { 0 : 1 },     
  delay:     800,            
  easing:   'expo.out'   
}).play();
```
[codepen demo](http://codepen.io/sol0mka/pen/JbLjRq?editors=0010)

If you have more complex animation it is nice to connect some tools to debug it, there is the demo with [mojs-player](https://github.com/legomushroom/mojs-player) tool:
```javascript

var animation = new mojs.Html({
  el:      '.element',      
  x:       { '-200' : 0 }, 
  opacity: { 0 : 1 }, 
  delay:   800,        
  easing:  'expo.out'
});

// create player and add the animation for debugging
new MojsPlayer({ add: animation });
```
[codepen demo](http://codepen.io/sol0mka/pen/MbVWKG?editors=0010)

Please let me know if you have more questions! Cheers ~

// @Madebym @sdras

**Comment by Madebym** [comment]
Thank you both! Much clearer now to me.

@sdras Yes, I've been using GSAP or Velocity before, nothing to complex. Just some subtle animations now and there. Thanks for the tips, especially the difference in easings.

@legomushroom I wasn't sure if HTML module was the one I needed, thanks for the clarification. I will close this now, I have more than enough to get my feet wet. Cheers

**Comment by legomushroom** [comment]
You are welcome! 👍 Cheers

**Comment by sdras** [comment]
Yay!
