### ISSUE TITLE
Unable to get property 'length' of undefined or null reference

### ISSUE THREAD

**Issue by JorgeCapillo** [legomushroom/mojs#91]
I just put the script in to the body and i get this error, i'm also working with a framework named 'Winjs'
The error is in 4618 line (not min)
`Tweener.prototype._restorePlayingTweens = function _restorePlayingTweens() {
 for (var i = 0; i < this._savedTweens.length; i++) {  // here (this._savedTweens is undefined)
	        this._savedTweens[i].resume();
	}
};
`

**Comment by legomushroom** [comment]
Hi Jorge!

That's weird, could you make a sample with the error, or just paste the snippet of the code the stack trace points to? It is hard to get into the error without more insights.

**Comment by JorgeCapillo** [comment]
sure
![captura](https://cloud.githubusercontent.com/assets/7957962/21283473/d59e119e-c3d0-11e6-863b-d298333f3f85.PNG)
i'm sorry for the image, i didn't know how put the code :)

**Comment by legomushroom** [comment]
I see. That's the bug that was covered already but those changes are not released yet. This can happen when you load the page in a background and then make that page active. However it should not affect any pieces of your, or mojs' code so you probably safe. I know that can be annoying and deeply sorry about that, will try to reseals the bug fix changes soon.

**Comment by JorgeCapillo** [comment]
ok then i follow with the dev, you take your time. Thanks so much for reply, i love mojs it's so amazing 😍   :') , also i'm awaiting for Iconmelon 🍉

**Comment by legomushroom** [comment]
Thank you!
