### ISSUE TITLE
Docs: Broken link Burst example

### ISSUE THREAD

**Issue by Sandstedt** [legomushroom/mojs#94]
The codepen example link is broken in the docs: https://github.com/legomushroom/mojs/blob/master/api/burst.md
Leads to: http://codepen.io/sol0mka/pen/JKWKVR?editors=0010

**Comment by legomushroom** [comment]
@Sandstedt why do you think it is broken?

**Comment by Sandstedt** [comment]
@legomushroom It returns a 404. Maybe it's private? Remember we had a similar issue way back.

**Comment by legomushroom** [comment]
@Sandstedt oh I see, please try now

**Comment by Sandstedt** [comment]
Works great! Thanks!
